### PR TITLE
fix deployment missing, #7

### LINKED ISSUE #7: Deployment section like in core
I have fixed this but cannot push into this repo.

### PR DESCRIPTION
**Pull request by karussell**
Fixes #7

### CODE REVIEW

**Comment by boldtrn** [comment]
We have to think about this. The problem is, every time we execute the create script, we are deleting the java folder, therefore this change would be lost with every execution of the create script. So we could remove the [line](https://github.com/boldtrn/graphhopper-routing-api-swagger/blob/master/create.sh#L53) that deletes the folder? On the other hand, we might break the client, as some files are not changed by the swagger codegen, if they already exist, for example the pom, tests, documentation, and so on. I think this is specifiable via the swagger-codegen.ignore file. 

So if we remove the delete line, we can merge this PR.

**Comment by boldtrn** [comment]
BTW: Something I realized while reviewing the code. Would it be possible to keep the change small (without reformatting the whole file?). It is a bit hard to review the actual changes, as it seems like the whole file was changed, but actually there are a lot of similarities.

**Comment by karussell** [comment]
Yes, will revert the format change and think about how to avoid overwriting this.

**Comment by karussell** [comment]
Have applied the change cleanly. Maybe we just re-apply this commit after any source update?

**Comment by boldtrn** [comment]
Should we close here since the repo does not contain java anymore?

**Pull request closed without merging**
