### PR TITLE
Added oms_key to geocoding results

### PR DESCRIPTION
**Pull request by boldtrn**

### CODE REVIEW

**Comment by karussell** [comment]
It is a bit ugly that swagger requires the parameter in the method instead of having a request object where you set the properties you want instead of filling out lots of null values...

**Comment by karussell** [comment]
For POST requests this is better. Is there something we can do about this for GET requests?

**Comment by karussell** [comment]
See eg. the mess for routing here: https://github.com/graphhopper/directions-api-java-client/blob/master/client-examples/src/main/java/com/graphhopper/directions/api/examples/RoutingExample.java#L23

**Comment by karussell** [comment]
The issue is kind of known already: https://github.com/swagger-api/swagger-codegen/issues/3819#issuecomment-303656309

**Comment by boldtrn** [comment]
Should we merge this then as well?

**Pull request merged**
