### PR TITLE
A polygon has an _array_ of coordinate _arrays_, not just one.

### PR DESCRIPTION
**Pull request by michaz**

### CODE REVIEW

**Comment by michaz** [comment]
How has this *ever* worked?? I think by accident, because arrays of numbers are not type-safe in what Swagger generates, so the code must (and can) cast in into anything it likes anyway. :-( :-( :-(

**Comment by michaz** [comment]
Just found this: Somebody has written down the Geometry data type in Swagger. Maybe we can just use that one as our return type. Don't know.

https://gist.github.com/bubbobne/fe5f2db65acf039be6a9fd92fc9c7233

**Comment by karussell** [comment]
Cool, thanks!

**Comment by karussell** [comment]
Cool, thanks!

**Pull request merged**
